---
# Source: rucio-ui/templates/deployment.yaml
apiVersion: v1
kind: Secret
metadata:
  name: usdf-rucio-ui.config.yaml
  labels:
    app: rucio-ui
    chart: rucio-ui-32.0.1
    release: "usdf"
    heritage: "Helm"
type: Opaque
data:
  common.json: "ewogICJkYXRhYmFzZSI6IHt9LAogICJwb2xpY3kiOiB7CiAgICAicGFja2FnZSI6ICJydWJpbiIKICB9Cn0="
---
# Source: rucio-ui/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: usdf-rucio-ui.cfg
  labels:
    app: rucio-ui
    chart: "rucio-ui-32.0.1"
    release: "usdf"
    heritage: "Helm"
type: Opaque
data:
  legacy_dn: "RmFsc2U="
  max_clients: "MjA="
  max_requests_per_child: "ODE5Mg=="
  max_spare_threads: "MjA="
  min_spare_threads: "MQ=="
  mpm_mode: "ZXZlbnQ="
  start_servers: "MQ=="
  threads_per_child: "NQ=="
---
# Source: rucio-ui/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: usdf-rucio-ui-aliases
  labels:
    app: usdf-rucio-ui
    chart: "rucio-ui-32.0.1"
    release: "usdf"
    heritage: "Helm"
data:
  aliases.conf: |+
    Alias /media        /opt/rucio/.venv/lib/python2.7/site-packages/rucio/web/ui/media
    Alias /static       /opt/rucio/.venv/lib/python2.7/site-packages/rucio/web/ui/static
    WSGIScriptAlias /   /opt/rucio/.venv/lib/python2.7/site-packages/rucio/web/ui/main.py
---
# Source: rucio-ui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: usdf-rucio-ui
  labels:
    app: rucio-ui
    chart: rucio-ui-32.0.1
    release: usdf
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: rucio-ui
    release: usdf
---
# Source: rucio-ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usdf-rucio-ui
  labels:
    app: rucio-ui
    chart: rucio-ui-32.0.1
    release: usdf
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rucio-ui
      release: usdf
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: rucio-ui
        release: usdf
      annotations:
        checksum/config: b2cb0a694e131e8da34c2802cc86d308d2f545c6
    spec:
      volumes:
      - name: config
        secret:
          secretName: usdf-rucio-ui.config.yaml
      - name: aliases
        configMap:
          name: usdf-rucio-ui-aliases
      - name: httpdlog
        emptyDir: {}
      - name: hostcert
        secret:
          secretName: usdf-hostcert
      - name: hostkey
        secret:
          secretName: usdf-hostkey
      - name: cafile
        secret:
          secretName: usdf-cafile
      - name: policy-package
        secret:
          secretName: usdf-policy-package
      containers:
        - name: httpd-error-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/httpd/error_log']
          volumeMounts:
          - name: httpdlog
            mountPath: /var/log/httpd
        - name: rucio-ui
          image: "rucio/rucio-ui:release-34.0.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /opt/rucio/etc/conf.d/10_common.json
              subPath: common.json
            - name: httpdlog
              mountPath: /var/log/httpd
            - name: aliases
              mountPath: /opt/rucio/etc/aliases.conf
              subPath: aliases.conf
            - name: hostcert
              mountPath: /etc/grid-security/hostcert.pem
              subPath: hostcert.pem
            - name: hostkey
              mountPath: /etc/grid-security/hostkey.pem
              subPath: hostkey.pem
            - name: cafile
              mountPath: /etc/grid-security/ca.pem
              subPath: ca.pem
            - name: policy-package
              mountPath: /opt/rucio/permissions/rubin
              subPath: 
          env:
            - name: RUCIO_HTTPD_LEGACY_DN
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-ui.cfg
                  key: legacy_dn
            - name: RUCIO_HTTPD_MAX_CLIENTS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-ui.cfg
                  key: max_clients
            - name: RUCIO_HTTPD_MAX_REQUESTS_PER_CHILD
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-ui.cfg
                  key: max_requests_per_child
            - name: RUCIO_HTTPD_MAX_SPARE_THREADS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-ui.cfg
                  key: max_spare_threads
            - name: RUCIO_HTTPD_MIN_SPARE_THREADS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-ui.cfg
                  key: min_spare_threads
            - name: RUCIO_HTTPD_MPM_MODE
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-ui.cfg
                  key: mpm_mode
            - name: RUCIO_HTTPD_START_SERVERS
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-ui.cfg
                  key: start_servers
            - name: RUCIO_HTTPD_THREADS_PER_CHILD
              valueFrom:
                secretKeyRef:
                  name: usdf-rucio-ui.cfg
                  key: threads_per_child
            - name: PYTHONPATH
              value: "/opt/rucio/permissions"

            - name: RUCIO_PROXY
              value: 
            - name: RUCIO_AUTH_PROXY
              value: 
            - name: RUCIO_DEFINE_ALIASES
              value: "True"
            - name: RUCIO_OVERRIDE_CONFIGS
              value: "/opt/rucio/etc/conf.d/"
            - name: RUCIO_LOG_FORMAT
              value: '[%{%Y-%m-%d %H:%M:%S}t]\t%v\t%h\t%{X-Forwarded-For}i\t%{X-Rucio-RequestId}i\t%>s\t%I\t%B\t%D\t\"%r\"\t\"%{X-Rucio-Auth-Token}i\"\t\"%{User-Agent}i\"\t%{X-Rucio-Script}i'
            - name: RUCIO_ENABLE_SSL
              value: "True"
          resources:
            {}
